#pragma once

#define FLOATNOTE_VERSION_MAJOR 2
#define FLOATNOTE_VERSION_MINOR 2
#define FLOATNOTE_VERSION_PATCH 0
#define FLOATNOTE_VERSION_BUILD 0

#define FLOATNOTE_VERSION_TUPLE 2, 2, 0, 0
#define FLOATNOTE_VERSION_STRING "2.2.0"
#define FLOATNOTE_FILE_VERSION_STRING "2.2.0.0\0"
#define FLOATNOTE_VERSION_WSTRING L"2.2.0"
